# Jekyll settings
source:         ./raw
destination:    ./public
plugins:        ./app/jekyll/plugins
permalink:      "/:year/:title/"

# Improved pagination
# https://github.com/mojombo/jekyll/pull/521
paginate:       5
paginate_files: blog/index.html
paginate_style: "/blog/page/:page/"

# Site settings
title: Van Patten Media
url: http://www.vanpattenmedia.com
