compress_assets:       on
gzip_assets:           off
javascript_compressor: uglifier
package_path:          javascripts

javascripts:
  script:
    - vendor/javascripts/jquery.videobg/0.2/*
    - app/assets/javascripts/video.js
    - app/assets/javascripts/script.js
