compress_assets:       on
gzip_assets:           off
javascript_compressor: uglifier
package_path:          assets/javascripts

javascripts:
  script:
    - app/assets/javascripts/script.js
  libraries:
    - vendor/javascripts/formalize/1.2/*.js
