compress_assets:       on
gzip_assets:           off
javascript_compressor: uglifier
package_path:          javascripts

javascripts:
  script:
    - app/assets/javascripts/script.js
  portfolio:
    - vendor/javascripts/jquery.tipsy/jquery.tipsy.js
    - app/assets/javascripts/portfolio.js
