compress_assets:       on
gzip_assets:           off
javascript_compressor: uglifier
package_path:          javascripts

javascripts:
  script:
    - vendor/javascripts/**/*.js
    - app/assets/javascripts/*.js
