compress_assets:       on
gzip_assets:           off
javascript_compressor: uglifier
package_path:          assets/javascripts

javascripts:
  script:
    - app/assets/javascripts/script.js
  libraries:
    - vendor/javascripts/formalize/1.2/*.js
    - vendor/javascripts/jquery.scrollTo/1.4.6/*.js
    - vendor/javascripts/jquery.localScroll/1.2.9b/*.js
  ie:
    - vendor/javascripts/html5shiv/3.6.2/*.js
    - vendor/javascripts/selectivizr/1.0.3b/*.js
    - vendor/javascripts/polyfill-rem/rem.js
    - vendor/javascripts/respond/1.1.0/*.js
