compress_assets:       on
gzip_assets:           off
javascript_compressor: uglifier
package_path:          javascripts

javascripts:
  script:
    - vendor/javascripts/jquery.cycle/jquery.cycle.all.js
    - vendor/javascripts/video.js/3.2.0/video.js
    - vendor/javascripts/bigvideo/bigvideo.js
    - app/assets/javascripts/video.js
    - app/assets/javascripts/slider.js
    - app/assets/javascripts/script.js
