name: vanpattenmedia
repo: git://github.com/vanpattenmedia/vanpattenmedia.com.git
user: vanpattenmedia
group: vanpattenmedia-sitewriters
deploy_user: deploy
access_users: [deploy, vanpattenmedia, chris, peter]
theme: vanpattenpress
domain: vanpattenmedia.com

stage:
  dev:
    ip: 127.0.0.1
    http_port: 15000
    ssh_port: 22000
    user: vagrant
    upload_url_path: http://uploads.vanpattenmedia.com/content/uploads 
    upload_path: ../../../../../uploads.vanpattenmedia.com/content/uploads
  staging:
    ip: 50.116.59.75
    ssh_port: 9012
    user: deploy
    upload_url_path: http://static.vanpattenmedia.com/content/uploads
    upload_path: ../../../../../uploads.vanpattenmedia.com/content/uploads
  production:
    ip: 50.116.59.75
    ssh_port: 9012
    user: deploy
    upload_url_path: http://static.vanpattenmedia.com/content/uploads
    upload_path: ../../../../../uploads.vanpattenmedia.com/content/uploads
