application:
  name: vanpattenmedia
  repo: git://github.com/vanpattenmedia/vanpattenmedia.com.git
  user: vanpattenmedia
  group: vanpattenmedia-sitewriters
  deploy_user: deploy
  access_users: [deploy, vanpattenmedia, chris, peter]
  theme: vanpattenpress
  domain: vanpattenmedia.com
  tbl_prefix: wp_
  servers:
    dev:
      ip: 127.0.0.1
      port: 22000
      user: vagrant
    staging:
      ip: 50.116.59.75
      port: 9012
      user: deploy
    production:
      ip: 50.116.59.75
      port: 9012
      user: deploy
